version: "3.8"
services:
  nginx:
      build: ./nginx
      container_name: nginx-container
      ports:
        - "42080:80"
      depends_on:
        - server
  server:
    build: ./server
    container_name: backend
    ports: 
      - '8000:8000'
  client:
    build: ./client
    container_name: frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
    volumes:
       - ./my-app:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules
     


